import type { Metadata } from "next";
import { SiteNav } from "@/components/site-nav";
import { PolicyLinks } from "@/components/policy-links";

export const metadata: Metadata = { title: "Privacy Policy", description: "How LeeMockups collects, uses, and protects personal information.", alternates: { canonical: "/privacy/" } };

export default function PrivacyPage() {
  return <main className="legal-page"><SiteNav /><article className="legal-shell shell">
    <header><span>LEGAL</span><h1>Privacy Policy</h1><p>Last updated: September 19, 2026</p></header>
    <section><h2>1. Scope</h2><p>This Privacy Policy explains how LeeMockups handles personal information when you visit leemockups.com, download or use the desktop application, purchase a digital product, or contact support.</p></section>
    <section><h2>2. Information we collect</h2><ul><li><strong>Website usage data:</strong> browser, device, approximate location, pages viewed, referral information, and similar analytics data.</li><li><strong>Support and feedback data:</strong> your email address, message, feedback type, current page address, and any screenshot you choose to attach.</li><li><strong>Order data:</strong> transaction identifiers, purchased products, payment status, country, and support information made available by our payment provider.</li><li><strong>Technical data:</strong> application version, operating system, and diagnostic details you voluntarily include in a support request.</li></ul><p>The LeeMockups desktop application processes imported artwork locally. It does not automatically upload your artwork, mockup projects, or finished exports to LeeMockups.</p></section>
    <section><h2>3. How we use information</h2><p>We use information to operate and secure the website, deliver purchased products, provide support, respond to feedback, prevent fraud and abuse, understand website performance, comply with legal obligations, and improve LeeMockups.</p></section>
    <section><h2>4. Legal bases</h2><p>Depending on your location, we process information to perform a contract, comply with law, pursue legitimate interests such as security and product improvement, or based on your consent. You may withdraw consent where processing relies on consent.</p></section>
    <section><h2>5. Service providers</h2><p>We use service providers only where needed to operate LeeMockups. These may include Cloudflare for hosting, security, content delivery, and file storage; Google Analytics for website measurement; FormSubmit for delivering feedback messages; and Paddle as Merchant of Record for checkout, tax, payment, fraud prevention, order support, and refunds. These providers process information under their own terms and privacy notices.</p></section>
    <section><h2>6. Cookies and analytics</h2><p>The website may use cookies or similar technologies for essential functionality, security, and analytics. Browser settings can limit cookies, although some features may work differently. We do not sell personal information.</p></section>
    <section><h2>7. Retention and security</h2><p>We retain information only as long as reasonably needed for support, delivery, security, accounting, dispute handling, and legal compliance. We use reasonable technical and organizational safeguards, but no internet service can guarantee absolute security.</p></section>
    <section><h2>8. International processing</h2><p>Our providers may process information in countries other than your own. Where required, transfers are protected using recognized legal safeguards.</p></section>
    <section><h2>9. Your rights</h2><p>Depending on your jurisdiction, you may request access, correction, deletion, restriction, portability, or objection to certain processing, and may complain to your local data-protection authority. We may need to verify your identity before completing a request.</p></section>
    <section><h2>10. Children</h2><p>LeeMockups is not directed to children under 13, and we do not knowingly collect personal information from children under 13.</p></section>
    <section><h2>11. Contact</h2><p>For privacy questions or requests, email <a href="mailto:support@leemockups.com">support@leemockups.com</a>. For information relating to a Paddle transaction, visit <a href="https://paddle.net" target="_blank" rel="noreferrer">paddle.net</a>.</p></section>
  </article><footer className="legal-footer shell"><strong>LeeMockups</strong><PolicyLinks /><span>© 2026 LeeMockups</span></footer></main>;
}
