import type { Metadata } from "next";
import { SiteNav } from "@/components/site-nav";
import { PolicyLinks } from "@/components/policy-links";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing the LeeMockups website, desktop application, and digital mockup products.", alternates: { canonical: "/terms/" } };

export default function TermsPage() {
  return <main className="legal-page"><SiteNav /><article className="legal-shell shell">
    <header><span>LEGAL</span><h1>Terms of Service</h1><p>Last updated: September 19, 2026</p></header>
    <section><h2>1. About LeeMockups</h2><p>LeeMockups provides desktop software and downloadable digital mockup templates that help customers place their own artwork into prepared scenes and export product videos and still images. These Terms apply to the LeeMockups website, software, templates, downloads, support, and related services.</p></section>
    <section><h2>2. Eligibility and acceptance</h2><p>By accessing the website, downloading the application, or purchasing or using a LeeMockups product, you agree to these Terms and the Refund Policy. You must be legally able to enter into a binding agreement in your country. If you use LeeMockups for an organization, you confirm that you are authorized to accept these Terms for it.</p></section>
    <section><h2>3. Products and delivery</h2><p>LeeMockups products are digital products; no physical goods are shipped. A product may include a <code>.mockup</code> template for use with the LeeMockups desktop application. Product pages describe the expected output, compatibility, resolution, duration, and included files. Delivery instructions and access information are provided after a successful payment.</p></section>
    <section><h2>4. Orders and payments</h2><p>Prices are shown before checkout. Applicable taxes may be added based on your location. Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle provides all customer service inquiries and handles returns. Paddle’s buyer terms and privacy notice also apply to transactions it processes.</p></section>
    <section><h2>5. License and permitted use</h2><p>Each purchase grants the buyer a limited, non-exclusive, non-transferable license to use the purchased template and the LeeMockups application to create exported videos and images. Exported results may be used in personal and commercial projects, including product listings, online shops, advertising, social media, and client presentations.</p><p>You may not resell, share, sublicense, distribute, publish, or make the original <code>.mockup</code> file or LeeMockups application available to another person. You may not reverse engineer, bypass access controls, or use the products to infringe another person’s intellectual-property or privacy rights.</p></section>
    <section><h2>6. Your artwork</h2><p>You retain ownership of artwork you import. You confirm that you have the rights required to use it. Desktop preview and export are performed locally on your computer; LeeMockups does not automatically upload your artwork.</p></section>
    <section><h2>7. Availability and updates</h2><p>We may improve, update, replace, or discontinue features when reasonably necessary. We aim to keep downloads available and products accurately described, but uninterrupted availability is not guaranteed. Compatibility may depend on your operating system, hardware, storage, and third-party system components.</p></section>
    <section><h2>8. Disclaimer and liability</h2><p>To the maximum extent permitted by law, LeeMockups is provided “as is” and “as available.” We do not guarantee that every template will suit every artwork or business purpose. We are not liable for indirect, incidental, special, or consequential losses. Nothing in these Terms excludes rights or liabilities that cannot lawfully be excluded, including mandatory consumer rights.</p></section>
    <section><h2>9. Suspension and termination</h2><p>We may restrict access where we reasonably believe there is fraud, payment abuse, unlawful activity, redistribution, security interference, or a material breach of these Terms. Legitimate customer access and mandatory consumer rights remain protected.</p></section>
    <section><h2>10. Changes and contact</h2><p>We may update these Terms to reflect product, legal, or operational changes. The current version and effective date will remain on this page. Questions about the product or these Terms may be sent to <a href="mailto:deaspliang@gmail.com">deaspliang@gmail.com</a>. Transaction and refund support for Paddle orders is also available through <a href="https://paddle.net" target="_blank" rel="noreferrer">paddle.net</a>.</p></section>
  </article><footer className="legal-footer shell"><strong>LeeMockups</strong><PolicyLinks /><span>© 2026 LeeMockups</span></footer></main>;
}
